apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector:
    app: kloudafrica
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: kloudafrica
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
