apiVersion: apps/v1
kind: Deployment
metadata:
  name: kloudafrica-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kloudafrica
  template:
    metadata:
      labels:
        app: kloudafrica
    spec:
      containers:
        - name: cache
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: cache-volume
              mountPath: /data
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: testdb
        - name: kloudafrica
          image: mbaoma/3tier-app
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://cache-service:6379
            - name: MONGODB_URI_LOCAL
              value: mongodb://mongo-service:27017/testdb

      volumes:
        - name: cache-volume
          emptyDir: {}
