#!/bin/bash
aws cloudformation create-stack \
  --stack-name kloud-africa-network \
  --template-body file://network.yml \
  --capabilities CAPABILITY_IAM

aws cloudformation wait stack-create-complete --stack-name kloud-africa-network

aws cloudformation create-stack \
  --stack-name kloud-africa-service \
  --template-body file://service.yml \
  --parameters \
      ParameterKey=StackName,ParameterValue=kloud-africa-network \
      ParameterKey=ServiceName,ParameterValue=kloud-africa-service \
      ParameterKey=ImageUrl,ParameterValue=docker.io/mbaoma/3tier-app:latest \
      ParameterKey=ContainerPort,ParameterValue=3000 \
      ParameterKey=HealthCheckPath,ParameterValue=/ \
      ParameterKey=HealthCheckIntervalSeconds,ParameterValue=30

aws cloudformation wait stack-create-complete --stack-name kloud-africa-service


